name: AI PR Review

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [ main, "**" ]

jobs:
  review:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      -  - name: Install deps
  run: npm i @actions/core @actions/github @octokit/rest openai@4.56.0

      - name: Run AI review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node .github/scripts/ai-pr-review.js
